package tom;

public enum ApiError {
	REQUEST_FAILED, USER_OBJECT_CONTAINS_ERRORS, USERNAME_ALREADY_TAKEN, FAILED_TO_DECRYPT_USER,
	CANT_UPDATE_OTHER_USERS, NOT_OWNED, NOT_FOUND, DOCUMENT_ALREADY_EXISTS, LLM_BUSY, FAILED_TO_CREATE_OR_UPDATE_ENTRY,
	FAILED_TO_ENUMERATE_PROJECT, FAILED_TO_CREATE_PROJECT, FAILED_TO_LIST_PROJECTS
}
